AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a tagged EC2 instance under the Free Tier without SSH access.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-01816d07b1128cd2d # Replace with the latest Amazon Linux 2 AMI for your region.
      # SecurityGroupIds:
      #   - !Ref InstanceSecurityGroup
      Tags:
        - Key: businessUnit
          Value: pesto-test-stack

  # InstanceSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties: 
  #     GroupDescription: Security group with no inbound rules
  #     SecurityGroupIngress: [] # No inbound rules, SSH access is disabled
  #     Tags:
  #       - Key: businessUnit
  #         Value: pesto-test-stack      

  # S3Bucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: pesto-test-bucket-905418490146 # Optional: Must be globally unique if specified.
  #     AccessControl: Private  # Optional: Access control for the bucket (Private, PublicRead, etc.).
  #     Tags:
  #       - Key: businessUnit
  #         Value: pesto-test-stack

Outputs:
  InstanceId:
    Description: The Instance ID of the created EC2 instance.
    Value: !Ref EC2Instance
  PublicIP:
    Description: The Public IP address of the created EC2 instance.
    Value: !GetAtt [EC2Instance, PublicIp]
  # BucketName:
  #   Description: Name of the created S3 bucket.
  #   Value: !Ref S3Bucket
  # BucketArn:
  #   Description: ARN of the created S3 bucket.
  #   Value: !GetAtt S3Bucket.Arn